### ISSUE TITLE
This package requires django-simple-captcha, it isn't clear why, but it quietly corrupts django-recaptcha installation

### ISSUE THREAD

**Issue by viktor-yunenko** [divio/aldryn-django-cms#142]
Many people want to use google recaptcha, one version or another. But it isn't easily configurable - at the moment there are no errors in the console, instead `django-simple-captcha` quietly corrupts `django-recaptcha` site-packages module on installation.

**Comment by FinalAngel** [comment]
@victor-yunenko we welcome a PR :)
