### ISSUE TITLE
Using MIGRATION_COMMANDS we can run the migrations in a transaction, check that every page doesn't return a server error and only then proceed with the real db migrations

### ISSUE THREAD

**Issue by viktor-yunenko** [divio/aldryn-django-cms#146]
I'm already doing it on djangocms-template project, [here's the respective command](https://gitlab.com/what-digital/djangocms-template/-/blob/d2859d13ecbf768064f7d8ae4eb939f923f16f10/settings.py#L332).

The command source code is part of djangocms-helpers package:
- https://gitlab.com/what-digital/djangocms-helpers/-/blob/master/djangocms_helpers/management/commands/test_pages_on_real_db.py
- https://gitlab.com/what-digital/djangocms-helpers/-/blob/master/djangocms_helpers/tests/test_pages.py

For now I'm checking all the registered admin pages and published django-cms pages.

But it looks as something that would be better suited for this repository?

**Comment by FinalAngel** [comment]
@victor-yunenko either here or aldryn-django, depending on if it's django-cms only.

**Comment by viktor-yunenko** [comment]
Since we're moving away from aldryn-django we probably won't need a PR.
