### ISSUE TITLE
This package requires psycopg2 < 2.8 (while 2.8.6 is working fine in practice), hence it isn't compatible with python 3.9

### ISSUE THREAD

**Issue by viktor-yunenko** [divio/aldryn-django-cms#156]
And it works with psycopg2 2.8.6 as far as I can see, but there's no way to compile requirements.txt at the moment.

**Comment by petrklus** [comment]
Ditto - similar issue with python 3.8

**Comment by petrklus** [comment]
Suggesting to remove the pin via https://github.com/divio/aldryn-django-cms/pull/159
