### ISSUE TITLE
Language options are not translated

### ISSUE THREAD

**Issue by Chive** [divio/aldryn-django-cms#90]
The language options configured in aldryn_config [here](https://github.com/aldryn/aldryn-django-cms/blob/support/3.4.x/aldryn_config.py#L150) are never translated into the user's language. Snippet:

```python
[
    {
        'code': code,
        'name': settings['ALL_LANGUAGES_DICT'][code],
        'fallbacks': [fbcode for fbcode in language_codes if fbcode != code],
        'public': True
    } for code in language_codes
]
```

Current (with user language set to German):

![before-lang](https://cloud.githubusercontent.com/assets/2700360/26403107/3eb8d176-408d-11e7-91e8-b5f927192858.png)

We should however, translate these into the user's language, using the following change:

```python
from django.utils.translation import ugettext_lazy

[
    {
        'code': code,
        'name': ugettext_lazy(settings['ALL_LANGUAGES_DICT'][code]),
        'fallbacks': [fbcode for fbcode in language_codes if fbcode != code],
        'public': True
    } for code in language_codes
]
```

to achieve this:

![after-lang](https://cloud.githubusercontent.com/assets/2700360/26403151/7becc098-408d-11e7-86e2-8a37bf146e48.png)

**Comment by stefanfoulis** [comment]
Maybe we should do it here already: https://github.com/aldryn/aldryn-django/blob/1.8.18.2/aldryn_config.py#L506
